<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <ModName>StationeersLibrary</ModName>
    <AssemblyName>$(ModName)</AssemblyName>
    <RootNamespace>$(ModName)</RootNamespace>

    <AnalysisLevel>latest-all</AnalysisLevel>
    <LangVersion>latest</LangVersion>
    <ErrorReport>none</ErrorReport>

    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>

    <RepositoryType>git</RepositoryType>
    <PackageProjectUrl>https://github.com/TerameTechYT/StationeersSharp</PackageProjectUrl>
    <RepositoryUrl>https://github.com/TerameTechYT/StationeersSharp</RepositoryUrl>
    <PackageLicenseFile>$(SolutionDir)LICENSE.md</PackageLicenseFile>
    <PackageReadmeFile>README.md</PackageReadmeFile>

    <PlatformTarget>x64</PlatformTarget>
    <Platforms>x64;x86</Platforms>
    <DebugType>embedded</DebugType>
    <WarningLevel>4</WarningLevel>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <!-- Import Stationeers VS properties - paths etc. -->
  <Import Project="$(SolutionDir)Stationeers.VS.props" />

  <!-- Import Game/Unity DLL references -->
  <Import Project="$(SolutionDir)Stationeers.VS.References.props" />
  <ItemGroup>
    <Compile Remove="Z:\VS Projects\StationeersSharp\Source\GlobalSuppressions.cs" />
  </ItemGroup>

</Project>