<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    <ItemGroup>
        <!-- System DLL's -->
        <SystemDll Include="$(StationeersManagedDirectory)\mscorlib.dll" />
        <SystemDll Include="$(StationeersManagedDirectory)\netstandard.dll" />
        <SystemDll Include="$(StationeersManagedDirectory)\System*.dll" />
        <SystemRefs Include="@(SystemDll->'%(Filename)')">
            <HintPath>$(StationeersManagedDirectory)\%(Identity).dll</HintPath>
            <Private>False</Private>
        </SystemRefs>
        <Reference Include="@(SystemRefs)" />

        <!-- BepInEx DLL's -->
        <BepInExDll Include="$(BIECoreDirectory)\BepInEx*.dll" />
        <BepInExRefs Include="@(BepInExDll->'%(Filename)')">
            <HintPath>$(BIECoreDirectory)\%(Identity).dll</HintPath>
            <Private>False</Private>
        </BepInExRefs>        
        <Reference Include="@(BepInExRefs)" />

        <!-- Harmony DLL's -->
        <Reference Include="0Harmony">
            <HintPath>$(BIECoreDirectory)\0Harmony.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="HarmonyXInterop">
            <HintPath>$(BIECoreDirectory)\HarmonyXInterop.dll</HintPath>
            <Private>False</Private>
        </Reference>

        <!-- StationeersLaunchPad DLL's -->
        <Reference Include="LaunchPadBooster">
            <HintPath>$(StationeersLaunchPadDirectory)\LaunchPadBooster.dll</HintPath>
            <Private>False</Private>
        </Reference>

        <!-- Mono DLL's -->
        <MonoDll Include="$(BIECoreDirectory)\Mono.Cecil*.dll" />
        <MonoRefs Include="@(MonoDll->'%(Filename)')">
            <HintPath>$(BIECoreDirectory)\%(Identity).dll</HintPath>
            <Private>False</Private>
        </MonoRefs>
        <Reference Include="@(MonoRefs)" />

        <!-- Game DLL's -->
        <Reference Include="Assembly-CSharp">
            <HintPath>$(StationeersManagedDirectory)\Assembly-CSharp.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="Assembly-CSharp-firstpass">
            <HintPath>$(StationeersManagedDirectory)\Assembly-CSharp-firstpass.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="Facepunch.Steamworks.Win64">
            <HintPath>$(StationeersManagedDirectory)\Facepunch.Steamworks.Win64.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="DOTween">
            <HintPath>$(StationeersManagedDirectory)\DOTween.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="Newtonsoft.Json">
            <HintPath>$(StationeersManagedDirectory)\Newtonsoft.Json.dll</HintPath>
            <Private>False</Private>
        </Reference>


        <!-- UniTask DLL's -->
        <UniTaskDll Include="$(StationeersManagedDirectory)\UniTask*.dll" />
        <UniTaskRefs Include="@(UniTaskDll->'%(Filename)')">
            <HintPath>$(StationeersManagedDirectory)\%(Identity).dll</HintPath>
            <Private>False</Private>
        </UniTaskRefs>
        <Reference Include="@(UniTaskRefs)" />

        <!-- ImGui DLL's -->
        <Reference Include="RG.ImGui">
            <HintPath>$(StationeersManagedDirectory)\RG.ImGui.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="RG.ImGui.Unity">
            <HintPath>$(StationeersManagedDirectory)\RG.ImGui.Unity.dll</HintPath>
            <Private>False</Private>
        </Reference>

        <!-- Unity DLL's -->
        <UnityDll Include="$(StationeersManagedDirectory)\Unity*.dll" />
        <UnityRefs Include="@(UnityDll->'%(Filename)')">
            <HintPath>$(StationeersManagedDirectory)\%(Identity).dll</HintPath>
            <Private>False</Private>
        </UnityRefs>
        <Reference Include="@(UnityRefs)" />
    </ItemGroup>
</Project>