<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
	<Import Project="$(SolutionDir)Stationeers.VS.User.props" />

	<PropertyGroup>
		<TargetFramework>net4.8</TargetFramework>
		<AnalysisLevel>latest-all</AnalysisLevel>
		<LangVersion>preview</LangVersion>
		<ErrorReport>none</ErrorReport>

		<NuGetAuditLevel>low</NuGetAuditLevel>
		<NuGetAuditMode>all</NuGetAuditMode>

		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>

		<RepositoryType>git</RepositoryType>
		<PackageProjectUrl>https://github.com/TerameTechYT/StationeersSharp</PackageProjectUrl>
		<RepositoryUrl>https://github.com/TerameTechYT/StationeersSharp</RepositoryUrl>
		<PackageLicenseFile>$(SolutionDir)LICENSE.md</PackageLicenseFile>
		<PackageReadmeFile>$(SolutionDir)README.md</PackageReadmeFile>

		<Configurations>Debug;Release;Publish</Configurations>
		<PlatformTarget>x64</PlatformTarget>
		<Platforms>x64;x86</Platforms>
		<DebugType>embedded</DebugType>
		<WarningLevel>4</WarningLevel>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<!-- Change this to the path to your Stationeers Directory -->
		<StationeersDirectory>$(SteamLibraryDirectory)\Stationeers</StationeersDirectory>

		<!-- Do Not Change Anything Below -->
		<StationeersDataDirectory>$(StationeersDirectory)\rocketstation_Data</StationeersDataDirectory>
		<StationeersManagedDirectory>$(StationeersDataDirectory)\Managed</StationeersManagedDirectory>
		<StationeersPluginsDirectory>$(StationeersDataDirectory)\Plugins</StationeersPluginsDirectory>
		<StationeersResourcesDirectory>$(StationeersDataDirectory)\Resources</StationeersResourcesDirectory>
		<StationeersStreamingAssetsDirectory>$(StationeersDataDirectory)\StreamingAssets</StationeersStreamingAssetsDirectory>
		<StationeersDocumentsDirectory>C:\Users\$(username)\Documents\My Games\Stationeers</StationeersDocumentsDirectory>

		<BIEDirectory>$(StationeersDirectory)\BepInEx</BIEDirectory>
		<BIECoreDirectory>$(BIEDirectory)\core</BIECoreDirectory>
		<BIEPatchersDirectory>$(BIEDirectory)\patchers</BIEPatchersDirectory>
		<BIEPluginsDirectory>$(BIEDirectory)\plugins</BIEPluginsDirectory>

		<StationeersLaunchPadDirectory>$(BIEPluginsDirectory)\StationeersLaunchPad</StationeersLaunchPadDirectory>
	</PropertyGroup>

	<Target Name="IncrementVersion" BeforeTargets="BeforeBuild" Condition="'$(Configuration)' != 'Publish'">
		<Exec Command="powershell -File &quot;$(SolutionDir)\Commands\Increment-Version.ps1&quot;" ContinueOnError="true" />
	</Target>

	<ItemGroup>
		<CopyItemsGameData Include="$(ProjectDir)\GameData\**\*.*" />
		<CopyItemsAbout Include="$(ProjectDir)\About\**\*.*" />
		<CopyItemsTextures Include="$(ProjectDir)\Textures\**\*.*" />
	</ItemGroup>

	<Target Name="PostBuild" AfterTargets="PostBuildEvent" Condition="'$(Configuration)' != 'Publish'">
		<RemoveDir Directories="$(StationeersDocumentsDirectory)\mods\$(ModName)" />
		<Copy SourceFiles="$(TargetPath)" DestinationFolder="$(StationeersDocumentsDirectory)\mods\$(ModName)" ContinueOnError="false" />
		<Copy SourceFiles="$(PackageLicenseFile)" DestinationFiles="$(StationeersDocumentsDirectory)\mods\$(ModName)\LICENSE.md" ContinueOnError="false" />
		<Copy SourceFiles="@(CopyItemsGameData)" DestinationFolder="$(StationeersDocumentsDirectory)\mods\$(ModName)\GameData\%(RecursiveDir)" ContinueOnError="true" />
		<Copy SourceFiles="@(CopyItemsAbout)" DestinationFolder="$(StationeersDocumentsDirectory)\mods\$(ModName)\About\%(RecursiveDir)" ContinueOnError="true" />
		<Copy SourceFiles="@(CopyItemsTextures)" DestinationFolder="$(StationeersDocumentsDirectory)\mods\$(ModName)\Textures\%(RecursiveDir)" ContinueOnError="true" />
	</Target>

	<ItemGroup>
		<!-- Extra File Compilations -->
		<Compile Include="$(SolutionDir)Source\GlobalSuppressions.cs" />

		<Compile Remove="bin\**" />
		<Compile Remove="obj\**" />
		<EmbeddedResource Remove="bin\**" />
		<EmbeddedResource Remove="obj\**" />
		<None Remove="bin\**" />
		<None Remove="obj\**" />

		<!-- README -->
		<None Update="README.md">
			<Pack>True</Pack>
			<PackagePath>$(SolutionDir)</PackagePath>
		</None>
	</ItemGroup>
</Project>