<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <ModName>StationpediaCalculator</ModName>
        <AssemblyName>$(ModName)</AssemblyName>
        <RootNamespace>$(ModName)</RootNamespace>
    </PropertyGroup>

    <!-- Import Stationeers VS properties - paths etc. -->
    <Import Project="$(SolutionDir)Stationeers.VS.props" />

    <!-- Import Game/Unity DLL references -->
    <Import Project="$(SolutionDir)Stationeers.VS.References.props" />

    <ItemGroup>
        <ProjectReference Include="$(SolutionDir)\Source\StationeersLibrary\StationeersLibrary.csproj" />
    </ItemGroup>
    
    <ItemGroup>
        <Reference Include="NCalc">
            <HintPath>NCalc.dll</HintPath>
            <Private>false</Private>
        </Reference>
    </ItemGroup>
</Project>