name: .NET Core Desktop

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Download SteamCMD
        uses: RageAgainstThePixel/setup-steamcmd@v1
    
      - name: Checkout Main Repository
        uses: actions/checkout@v4

      - name: Install .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Download Stationeers
        run: steamcmd +login anonymous +sDepotDownloadFileFilter "*.dll" +app_update 600760 validate +quit

      - name: Copy Libraries
        run: |
          mkdir Libraries
          cp $STEAM_DIR/steamapps/common/Stationeers\ Dedicated\ Server/rocketstation_DedicatedServer_Data/Managed/*.dll ./Libraries

      - name: Download BepInEx
        run: |
          Invoke-WebRequest -Uri "https://github.com/BepInEx/BepInEx/releases/download/v5.4.22/BepInEx_x64_5.4.22.0.zip" -OutFile "bepinex.zip"
          Expand-Archive -Path "bepinex.zip" -DestinationPath "bepinex"
          cp ./bepinex/core/*.dll ./Libraries

      - name: Download StationeersLaunchPad  
        run: |
          Invoke-WebRequest -Uri "https://github.com/StationeersLaunchPad/StationeersLaunchPad/releases/download/v0.2.12/StationeersLaunchPad-v0.2.12.zip" -OutFile "slp.zip"
          Expand-Archive -Path "slp.zip" -DestinationPath "slp"
          cp ./slp/StationeersLaunchPad/*.dll ./Libraries

      - name: Build Solution
        run: |
          msbuild StationeersSharp.sln `
            /p:Configuration=Publish `
            /p:Platform="x64" `
            /restore
          dir /a

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Mods
          path: Build/Publish/x64
